;;; flycheck-golangci-lint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-golangci-lint.el

(autoload 'flycheck-golangci-lint-setup "flycheck-golangci-lint" "\
Setup Flycheck GolangCI-Lint.
Add `golangci-lint' to `flycheck-checkers'." t)

;;; End of scraped data

(provide 'flycheck-golangci-lint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-golangci-lint-autoloads.el ends here
