;;; mediawiki-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mediawiki-api.el

(register-definition-prefixes "mediawiki-api" '("mediawiki-"))


;;; Generated autoloads from mediawiki-auth.el

(autoload 'mediawiki-do-login "mediawiki-auth" "\
Log into SITENAME using USERNAME, PASSWORD and DOMAIN.
Store cookies for future authentication.

(fn &optional SITENAME USERNAME PASSWORD)" t)
(autoload 'mediawiki-do-logout "mediawiki-auth" "\
Log out of SITENAME.

(fn &optional SITENAME)" t)
(register-definition-prefixes "mediawiki-auth" '("mediawiki-log"))


;;; Generated autoloads from mediawiki-core.el

(register-definition-prefixes "mediawiki-core" '("mediawiki-"))


;;; Generated autoloads from mediawiki-draft.el

(autoload 'mediawiki-draft-view-draft "mediawiki-draft" "\
Simple shortcut to visit the drafts file." t)
(autoload 'mediawiki-draft "mediawiki-draft" "\
Open a temporary buffer in mediawiki-mode.
This is for editing a draft.  After finishing the editing either
use \\[mediawiki-draft-buffer] to send the data into the
mediawiki-draft-data-file, or send the buffer using
\\[mediawiki-save] and insert it later into a mediawiki article." t)
(autoload 'mediawiki-draft-page "mediawiki-draft" "\
Set the current buffer as a draft buffer." t)
(autoload 'mediawiki-draft-region "mediawiki-draft" "\
Mediawiki-draft the data from BEGIN to END.
If called from within the mediawiki-draft buffer, BEGIN and END are ignored,
and the entire buffer will be mediawiki-drafted.  If called from any other
buffer, that region, plus any context information specific to that
region, will be mediawiki-drafted.

(fn &optional BEGIN END)" t)
(autoload 'mediawiki-draft-buffer "mediawiki-draft" "\
Mediawiki-draft-buffer sends the contents of the current (temporary)
buffer to the mediawiki-draft-buffer, see the variable
mediawiki-draft-data-file." t)
(autoload 'mediawiki-draft-clipboard "mediawiki-draft" "\
Mediawiki-Draft the contents of the current clipboard.
Most useful for mediawiki-drafting things from Netscape or other X Windows
application." t)
(autoload 'mediawiki-draft-copy-page-to-register "mediawiki-draft" "\
Copy a page via the mediawiki-draft-register." t)
(autoload 'mediawiki-draft-yank-page-to-register "mediawiki-draft" "\
Insert a page via the mediawiki-draft-register." t)
(autoload 'mediawiki-draft-send "mediawiki-draft" "\
Copy the current page in the drafts file to TARGET-BUFFER.
If `mediawiki-draft-send-archive' is t, then additionally the
text will be archived in the draft.wiki file.

(fn TARGET-BUFFER)" t)
(autoload 'mediawiki-draft-reply "mediawiki-draft" "\
Open a temporary buffer to edit a draft.
After finishing the editing: either use `mediawiki-draft-buffer'
to send the data into the `mediawiki-draft-data-file'.  Check the
variable `mediawiki-draft-send-archive'." t)
(register-definition-prefixes "mediawiki-draft" '("mediawiki-draft-"))


;;; Generated autoloads from mediawiki-faces.el

(register-definition-prefixes "mediawiki-faces" '("font-mediawiki-"))


;;; Generated autoloads from mediawiki-font-lock.el

(register-definition-prefixes "mediawiki-font-lock" '("mediawiki-"))


;;; Generated autoloads from mediawiki-http.el

(register-definition-prefixes "mediawiki-http" '("url-"))


;;; Generated autoloads from mediawiki-mode.el

(autoload 'mediawiki-next-header "mediawiki-mode" "\
Move point to the end of the next section header." t)
(autoload 'mediawiki-prev-header "mediawiki-mode" "\
Move point to the start of the previous section header." t)
(autoload 'mediawiki-terminate-paragraph "mediawiki-mode" "\
End a paragraph by any means necessary.
In a list, start a new list item; in a paragraph, start a new paragraph;
if the current paragraph is colon indented, the new
paragraph will be indented in the same way." t)
(autoload 'mediawiki-terminate-paragraph-and-indent "mediawiki-mode" "\
In a list, start a new list item.
In a paragraph, start a new paragraph but *,# will be ignored; if
the current paragraph is colon indented, the new paragraph will
be indented in the same way." t)
(autoload 'mediawiki-fill-article "mediawiki-mode" "\
Fill the entire article." t)
(autoload 'mediawiki-unfill-article "mediawiki-mode" "\
Undo filling, deleting stand-alone newlines.
Stand-alone newlines are those that do not end paragraphs, list
entries, etc." t)
(autoload 'mediawiki-reply-at-point-simple "mediawiki-mode" "\
Very simple function to reply to posts in the discussion forum.
You have to set the point around the signature, then the
functions inserts the following
:'''Re: [[User:foo]]'''." t)
(autoload 'mediawiki-goto-previous-page "mediawiki-mode" "\
Pop up the previous page being editted." t)
(autoload 'mediawiki-goto-next-page "mediawiki-mode" "\
Pop up the previous page being editted." t)
(autoload 'mediawiki-goto-next-link "mediawiki-mode" "\
Go to the next link in the page." t)
(autoload 'mediawiki-goto-prev-link "mediawiki-mode" "\
Go to the previous link in the page." t)
(autoload 'mediawiki-insert-enumerate "mediawiki-mode" "\
Primitive function for inserting enumerated items.
Check the variable mediawiki-enumerate-with-terminate-paragraph.
Note however that the function \\[mediawiki-terminate-paragraph]
does not work very well will longlines-mode." t)
(autoload 'mediawiki-insert-itemize "mediawiki-mode" "\
Primitive function for inserting no enumerated items.
Check the variable mediawiki-enumerate-with-terminate-paragraph.
Note however that the function \\[mediawiki-terminate-paragraph]
does not work very well will longlines-mode." t)
(autoload 'mediawiki-insert-strong-emphasis "mediawiki-mode" "\
Mark with strong emphasis italics.
Uses four apostrophes (e.g. ''''FOO'''').  When mark is active,
surrounds region." t)
(autoload 'mediawiki-insert-bold "mediawiki-mode" "\
Mark bold.
Uses three apostrophes (e.g. '''FOO''').  When mark is active,
surrounds region." t)
(autoload 'mediawiki-insert-italics "mediawiki-mode" "\
Mark italics.
Uses TWO apostrophes (e.g. ''FOO'').  When mark is active,
surrounds region." t)
(autoload 'mediawiki-insert-quotation-with-signature "mediawiki-mode" "\
Mark the current region as a quotation with your signature." t)
(autoload 'mediawiki-insert-quotation "mediawiki-mode" "\
Mark the current selection as a quote.
Use the form {{Quotation}}{{}}.  When mark is active,
surrounds region." t)
(autoload 'mediawiki-insert-bible-verse-template "mediawiki-mode" "\
Insert a template for the quotation of Bible verses." t)
(autoload 'mediawiki-insert-user "mediawiki-mode" "\
Interactively insert a user name." t)
(autoload 'mediawiki-insert-reply-prefix "mediawiki-mode" "\
Quotation box of the form {{Quotation}}{{}}." t)
(autoload 'mediawiki-insert-header "mediawiki-mode" "\
Insert subheader via == (e.g. == FOO ==)." t)
(autoload 'mediawiki-insert-link "mediawiki-mode" "\
Insert link (e.g. [[FOO]])." t)
(autoload 'mediawiki-insert-link-www "mediawiki-mode" "\
Insert link (e.g. [://FOO])." t)
(autoload 'mediawiki-insert-image "mediawiki-mode" "\
Insert image link (e.g. [[Image:FOO]]).
Checks the variable mediawiki-english-or-german." t)
(autoload 'mediawiki-insert-audio "mediawiki-mode" "\
Insert audio link (e.g. [[Media:FOO]])
Checks The variable mediawiki-english-or-german." t)
(autoload 'mediawiki-insert-signature "mediawiki-mode" "\
Insert signature (e.g. \"~~~~:\")." t)
(autoload 'mediawiki-insert-hline "mediawiki-mode" "\
Insert hline (e.g. \"----\")." t)
(autoload 'mediawiki-unfill-paragraph-or-region "mediawiki-mode" "\
Unfill region.
This function does NOT explicitly search for \"soft newlines\"
as does mediawiki-unfill-region." t)
(autoload 'mediawiki-start-paragraph "mediawiki-mode" "\
Start a Paragraph." t)
(autoload 'mediawiki-hardlines "mediawiki-mode" "\
Set `use-hard-newlines' to NIL." t)
(autoload 'mediawiki-next-long-line "mediawiki-mode" "\
Move forward to the next long line.
Lines are considered long if their length is greater than `fill-column'.

TODO: When function reaches end of buffer, `save-excursion' to starting
point.  Generalise to make `previous-long-line'." t)
(autoload 'mediawiki-unfill-paragraph-simple "mediawiki-mode" "\
A very simple function for unfilling a paragraph." t)
(autoload 'mediawiki-outline-magic-keys "mediawiki-mode" "\
Set up outline magic keys.
See https://www.emacswiki.org/emacs/OutlineMagic" t)
(autoload 'mediawiki-enhance-indent "mediawiki-mode" "\
Indent a region using MediaWiki markup (e.g \":\")." t)
(autoload 'mediawiki-yank-prefix "mediawiki-mode" "\
Remove indent markup from region.
FIXME!!!" t)
(autoload 'mediawiki-simple-outline-promote "mediawiki-mode" "\
Simple-minded promotion of current line.
This function simply deletes one \"=\" from the beginning and end
of the line.  It does not promote the whole tree!" t)
(autoload 'mediawiki-simple-outline-demote "mediawiki-mode" "\
Simple-minded demotion of the current line.
This function simple adds \"=\" to the beginning and end of the
line.  It does not promote the whole tree!" t)
(autoload 'mediawiki-rename-buffer "mediawiki-mode" "\
Make sure that the option UNIQUE is used." t)
(autoload 'mediawiki-mark-section "mediawiki-mode" "\
Set mark at end of current logical section, and point at top." t)
(autoload 'mediawiki-mark-signature "mediawiki-mode" "\
Set mark at end of current logical section, and point at top." t)
(autoload 'mediawiki-reload "mediawiki-mode" "\
Reload the page from the server." t)
(autoload 'mediawiki-mode "mediawiki-mode" "\
Major mode for editing articles written in MediaWiki's wikitext.

Wikipedia articles are usually unfilled: newline characters are not used
for breaking paragraphs into lines.  In case something goes wrong, the
following commands may come in handy:

\\[mediawiki-fill-article] fills the buffer.
\\[mediawiki-unfill-article] unfills the buffer.

Be warned that function can be dead slow, better use
`mediawiki-unfill-paragraph-or-region'.
\\[mediawiki-unfill-paragraph-or-region] unfills the paragraph
\\[mediawiki-unfill-paragraph-simple] does the same but simpler.

The following commands put in markup structures.
\\[mediawiki-insert-strong-emphasis] inserts italics
\\[mediawiki-insert-bold] inserts bold text
\\[mediawiki-insert-italics] italics
\\[mediawiki-insert-header] header
\\[mediawiki-insert-link] inserts a link

The following commands are also defined:
\\[mediawiki-insert-user] inserts user name
\\[mediawiki-insert-signature] inserts ~~~~
\\[mediawiki-insert-enumerate] inserts enumerate type structures
\\[mediawiki-insert-itemize] inserts itemize type structures
\\[mediawiki-insert-hline] inserts a hline

Replying functionality
\\[mediawiki-reply-at-point-simple]

The register functionality
\\[mediawiki-copy-page-to-register]
\\[defun mediawiki-insert-page-to-register]

Some simple editing commands.
\\[mediawiki-enhance-indent]
\\[mediawiki-yank-prefix]
\\[mediawiki-unfill-paragraph-or-region]

\\[mediawiki-terminate-paragraph] starts a new list item or paragraph in
a context-aware manner.
\\[mediawiki-next-header]     moves to the next (sub)section header.
\\[mediawiki-prev-header]     moves to the previous (sub)section header.

(fn)" t)
(autoload 'mediawiki-file-mode "mediawiki-mode" "\
Major mode for editing MediaWiki markup in local files.

This mode derives from `mediawiki-mode' but replaces the save and open
keybindings to work with local files instead of wiki pages:

\\[save-buffer] saves the current buffer to its file.
\\[save-buffer-as] saves the current buffer to a different file.
\\[find-file] opens a local file.
\\[kill-buffer-and-window] saves and closes the current buffer.

All other MediaWiki editing functionality remains the same.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.wiki\\'" . mediawiki-file-mode))
(add-to-list 'auto-mode-alist '("\\.mediawiki\\'" . mediawiki-file-mode))
(register-definition-prefixes "mediawiki-mode" '("mediawiki-"))


;;; Generated autoloads from mediawiki-page.el

(autoload 'mediawiki-open "mediawiki-page" "\
Open a wiki page specified by NAME from the mediawiki engine.

(fn NAME)" t)
(autoload 'mediawiki-save "mediawiki-page" "\
Save the current buffer as a page on the current site.
Prompt for a SUMMARY if one isn't given.

(fn &optional SUMMARY)" t)
(autoload 'mediawiki-save-on "mediawiki-page" "\
On SITENAME, save a page with NAME and SUMMARY.

(fn &optional SITENAME NAME SUMMARY)" t)
(autoload 'mediawiki-save-as "mediawiki-page" "\
Save a page on the current site wite NAME and SUMMARY.

(fn &optional NAME SUMMARY)" t)
(autoload 'mediawiki-save-and-bury "mediawiki-page" "\
Prompt for a SUMMARY, save the page, then bury the buffer.

(fn &optional SUMMARY)" t)
(autoload 'mediawiki-open-page-at-point "mediawiki-page" "\
Open a new buffer with the page at point." t)
(register-definition-prefixes "mediawiki-page" '("mediawiki-"))


;;; Generated autoloads from mediawiki-site.el

(autoload 'mediawiki-browse "mediawiki-site" "\
Open the BUFFER in a browser.
If BUFFER is not given, the current buffer is used.

(fn &optional BUFFER)" t)
(autoload 'mediawiki-site "mediawiki-site" "\
Set up mediawiki.el for a SITE.
Without an argument, use `mediawiki-site-default'.
Interactively, prompt for a SITE.

(fn &optional SITE)" t)
(register-definition-prefixes "mediawiki-site" '("mediawiki-"))


;;; Generated autoloads from mediawiki-utils.el

(register-definition-prefixes "mediawiki-utils" '("mediawiki-"))

;;; End of scraped data

(provide 'mediawiki-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mediawiki-autoloads.el ends here
