;;; auto-virtualenvwrapper-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from auto-virtualenvwrapper.el

(autoload 'auto-virtualenvwrapper-activate "auto-virtualenvwrapper" "\
Activate virtualenv for buffer-filename.
If invoked with prefix command argument, cached information is ignored.
Set `auto-virtualenvwrapper-auto-deactivate' to t, if you want deactivate
automatically at visiting the buffer not related to any virtualenv.

(fn &optional IGNORE-CACHE)" t)
(register-definition-prefixes "auto-virtualenvwrapper" '("auto-virtualenvwrapper-"))

;;; End of scraped data

(provide 'auto-virtualenvwrapper-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auto-virtualenvwrapper-autoloads.el ends here
