#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

[ -s "/home/srokadia/.kre/kvm/kvm.sh" ] && . "/home/srokadia/.kre/kvm/kvm.sh" # Load kvm

PATH=$PATH:$HOME/.gem/ruby/2.3.0/bin

[ -s "/home/srokadia/.dnx/dnvm/dnvm.sh" ] && . "/home/srokadia/.dnx/dnvm/dnvm.sh" # Load dnvm

PATH=$PATH:$HOME/.gem/ruby/2.3.0/bin
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
