#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

xmodmap ~/.xmodmap

eval $(keychain --eval --agents ssh -Q --quiet ~/.ssh/nexusssh_rsa)