export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
# set the cursor
xsetroot -cursor_name left_ptr
xmodmap ~/.xmodmap

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# start xmonad
exec xcompmgr -n & xmonad
