#!/bin/sh

#
# ~/.xprofile
#
# Executed by gdm at login
#

# ~/.dropbox-dist/dropboxd &
if [ -f ~/wallpapers/arch-linux-1.png ]; then
    xloadimage -onroot -zoom 50 -display $DISPLAY ~/wallpapers/arch-linux-1.png
fi

if [ -f ~/.xmodmap ]; then
    xmodmap ~/.xmodmap
fi

if [ -x $(command -v autorandr) ]; then
    autorandr -c
fi

