#!/bin/sh

#
# ~/.xprofile
#
# Executed by gdm at login
#

# ~/.dropbox-dist/dropboxd &
if [ -f ~/Downloads/wallpapers/arch-linux-1.jpg ]; then
    xloadimage -onroot -display $DISPLAY ~/Downloads/wallpapers/arch-linux-1.jpg
fi

if [ -f ~/.xmodmap ]; then
    xmodmap ~/.xmodmap
fi

if [ -x $(command -v autorandr) ]; then
    autorandr -c
fi

