export PATH="$PATH:/home/srokadia/scripts:/home/srokadia/.gem/ruby/2.3.0/bin"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/srokadia/scripts:/home/srokadia/.gem/ruby/2.3.0/bin:$PATH"
