;;; todoist-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from todoist.el

(autoload 'todoist "todoist" "\
Main function to summon the todoist dashboard as 'org-mode'." t)
(register-definition-prefixes "todoist" '("todoist-"))

;;; End of scraped data

(provide 'todoist-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; todoist-autoloads.el ends here
