;;; jsonnet-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jsonnet-mode.el

(autoload 'jsonnet-mode "jsonnet-mode" "\
jsonnet-mode is a major mode for editing .jsonnet files.

(fn)" t)
(add-to-list 'auto-mode-alist (cons "\\.jsonnet\\'" 'jsonnet-mode))
(add-to-list 'auto-mode-alist (cons "\\.libsonnet\\'" 'jsonnet-mode))
(autoload 'jsonnet-eval-buffer "jsonnet-mode" "\
Run jsonnet with the path of the current file." t)
(autoload 'jsonnet-jump-to-definition "jsonnet-mode" "\
Jump to the definition of the jsonnet function IDENTIFIER.

(fn IDENTIFIER)" t)
(autoload 'jsonnet-jump "jsonnet-mode" "\
Jumps to the definition of the Jsonnet expression at POINT.

(fn _)" t)
(autoload 'jsonnet-reformat-buffer "jsonnet-mode" "\
Reformat entire buffer using the Jsonnet format utility." t)
(register-definition-prefixes "jsonnet-mode" '("jsonnet-"))

;;; End of scraped data

(provide 'jsonnet-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jsonnet-mode-autoloads.el ends here
