(require 'key-chord)
(key-chord-mode 1)
(key-chord-define-global "jk" 'find-file)
(key-chord-define-global "jo" 'other-window)
(key-chord-define-global "jp" '(lambda () (interactive) (other-window -1)))
(key-chord-define-global "j]" '(lambda () (interactive) (other-window -1) (delete-window)))
(key-chord-define-global "ji" 'ido-switch-buffer)
(key-chord-define-global "je" 'delete-window)
(key-chord-define-global "jd" 'delete-other-windows)
(key-chord-define-global "jr" '(lambda () (interactive) (delete-other-windows) (split-window-right) (other-window 1)))
(key-chord-define-global "jw" 'remove-compile-windows)
(key-chord-define-global "fk" 'split-window-below)
(key-chord-define-global "fl" 'split-window-right)

(key-chord-define-global "sj" 'term-paste)

(key-chord-define-global "df" 'find-file-in-repository)
(key-chord-define-global "fg" 'find-name-dired)
(key-chord-define-global "gk" 'goto-line)
(key-chord-define-global "sd" 'find-file-in-repository-other-window)
(key-chord-define-global ",." '(lambda () (interactive) (other-window -1) (ido-switch-buffer)))
(key-chord-define-global "m," 'other-frame)
(key-chord-define-global "x9" 'delete-other-windows)
(key-chord-define-global "cv" '(lambda () (interactive) (helm-grep-do-git-grep t)))
(key-chord-define-global "cb" 'rgrep)
(key-chord-define-global "gh" 'vc-git-view)
(key-chord-define-global ";'" 'vc-git-blame)
(key-chord-define-global "p[" 'tide-references)
(key-chord-define-global "fj" 'yas-expand)
(key-chord-define-global "vl" 'flycheck-buffer)
(key-chord-define-global "vj" 'flycheck-next-error)
(key-chord-define-global "vk" 'flycheck-previous-error)
(key-chord-define-global "xl" 'flymake-show-diagnostics-buffer)
(key-chord-define-global "xj" 'flymake-goto-next-error)
(key-chord-define-global "xk" 'flymake-goto-prev-error)
(key-chord-define-global "cx" 'ace-jump-mode)
(key-chord-define-global "xi" 'eval-print-last-sexp)
(key-chord-define-global "qj" 'kill-ring-save-sexp)

(setq key-chord-two-keys-delay 0.02)
