(when (package-installed-p 'key-chord)
  (require 'key-chord)
  (key-chord-mode 1)
  (key-chord-define-global "jk" 'find-file)
  (key-chord-define-global "kl" 'find-file-other-window)
  (key-chord-define-global "zx" 'other-window)
  (key-chord-define-global "df" 'find-file-in-repository)
  (key-chord-define-global "sd" 'find-file-in-repository-other-window)
  (key-chord-define-global "qw" 'ido-switch-buffer)
  (key-chord-define-global ",." '(lambda () (interactive) (ido-switch-buffer-other-window) (other-window -1)))
  (key-chord-define-global "m," 'other-frame)
  (key-chord-define-global "x0" 'delete-window)
  (key-chord-define-global "cv" 'rgrep)
  (key-chord-define-global "x-" 'split-window-below)
  (key-chord-define-global "x\\" 'split-window-right)
  (key-chord-define-global "l;" 'wg-switch-to-workgroup)
  (key-chord-define-global "gh" 'vc-git-view)
  (key-chord-define-global ";'" 'vc-git-blame)
  (key-chord-define-global "p[" 'tide-references)
  (key-chord-define-global "vl" 'flycheck-buffer)
  (key-chord-define-global "vj" 'flycheck-next-error)
  (key-chord-define-global "vk" 'flycheck-previous-error)
  (key-chord-define-global "cx" 'ace-jump-mode)
  (key-chord-define-global "xi" 'eval-print-last-sexp)
  (setq key-chord-two-keys-delay 0.02))
