(when (package-installed-p 'key-chord)
  (require 'key-chord)
  (key-chord-mode 1)
  (key-chord-define-global "jk" 'find-file)
  (key-chord-define-global "kl" 'find-file-other-window)
  (key-chord-define-global "yu" 'other-window)
  (key-chord-define-global "df" 'find-file-in-repository)
  (key-chord-define-global "sd" 'find-file-in-repository-other-window)
  (key-chord-define-global "er" 'ido-switch-buffer)
  (key-chord-define-global "ui" 'ido-switch-buffer-other-window)
  (key-chord-define-global "x0" 'delete-window)
  (key-chord-define-global "cv" 'rgrep)
  (key-chord-define-global "x-" 'split-window-below)
  (key-chord-define-global "x\\" 'split-window-right)
  (key-chord-define-global "we" 'wg-switch-to-workgroup)
  (key-chord-define-global ",." 'vc-hg-view)
  (key-chord-define-global "./" 'vc-hg-blame)
  (setq key-chord-two-keys-delay 0.02))
