;;; code-stats-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from code-stats.el

(autoload 'code-stats-mode "code-stats" "\
Code Stats Minor Mode.

This is a minor mode.  If called interactively, toggle the
`Code-Stats mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `code-stats-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'code-stats-sync "code-stats" "\
Sync with Code::Stats.
If WAIT is non-nil, block Emacs until the process is done.

(fn &optional WAIT)")
(register-definition-prefixes "code-stats" '("code-stats-"))

;;; End of scraped data

(provide 'code-stats-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; code-stats-autoloads.el ends here
